//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitasSalonApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int Id { get; set; }
        public string descripcion { get; set; }
        public string numero_deposito { get; set; }
    
        public virtual EstadoCita EstadoCita { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual DetalleFechaBloque DetalleFechaBloque { get; set; }
    }
}
