//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitasSalonApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFechaBloque
    {
        public int Id { get; set; }
        public int HoraId { get; set; }
        public int FechaId { get; set; }
    
        public virtual Hora Hora { get; set; }
        public virtual Fecha Fecha { get; set; }
        public virtual EstadoHorario EstadoHorario { get; set; }
        public virtual Cita Cita { get; set; }
    }
}
